SELECT AUTHOR_ID
    , AUTHOR_NAME
    , CATEGORY
    , SUM(SALES * PRICE) AS TOTAL_SALES 
    # , AUTHOR_NAME
    # , CATEGORY
    # , SUM(SALES) * PRICE AS TOTAL_SALES
FROM BOOK
JOIN BOOK_SALES
    USING(BOOK_ID)
JOIN AUTHOR
    USING(AUTHOR_ID)
# WHERE SALES_DATE <= "20220131"
WHERE MONTH(SALES_DATE) = 1
GROUP BY AUTHOR_ID, CATEGORY
ORDER BY AUTHOR_ID, CATEGORY DESC