WITH MILK AS(
    SELECT ID,CART_ID, NAME, PRICE
    FROM CART_PRODUCTS
    WHERE NAME = 'MILK'
),
YOGURT AS(
    SELECT ID,CART_ID, NAME, PRICE
    FROM CART_PRODUCTS
    WHERE NAME = 'YOGURT'
)

SELECT DISTINCT CART_ID
FROM MILK
JOIN YOGURT
    USING(CART_ID)
ORDER BY CART_ID