SELECT ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO AS I
LEFT JOIN (
    SELECT DISTINCT PARENT_ITEM_ID
    FROM ITEM_TREE
) AS T
    ON ITEM_ID = PARENT_ITEM_ID
WHERE T.PARENT_ITEM_ID IS NULL
ORDER BY ITEM_ID DESC