SELECT DATE_FORMAT(SALES_DATE, "%Y-%m-%d") AS SALES_DATE, 
    PRODUCT_ID, 
    USER_ID, 
    SALES_AMOUNT
FROM (
    (SELECT SALES_DATE, PRODUCT_ID, 
      USER_ID, 
      SALES_AMOUNT
    FROM ONLINE_SALE) 
    UNION
    (SELECT SALES_DATE, PRODUCT_ID, 
     NULL AS USER_ID,
     SALES_AMOUNT
    FROM OFFLINE_SALE)
    ) AS T
    
WHERE MONTH(SALES_DATE) = 3
ORDER BY SALES_DATE, PRODUCT_ID, USER_ID