-- 코드를 입력하세요
SELECT CAR_ID, CAR_TYPE, FLOOR(DAILY_FEE*30 *(100-DISCOUNT_RATE)/100)  AS FEE
FROM CAR_RENTAL_COMPANY_CAR AS CAR
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS PLAN
    USING(CAR_TYPE)
WHERE DURATION_TYPE LIKE "30%"
    && (CAR_TYPE = "세단" || CAR_TYPE = "SUV")
    && CAR.CAR_ID NOT IN(
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE START_DATE <= "20221130" && END_DATE >= "20221101"
    )
    
HAVING 500000 <= FEE&&FEE < 2000000
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC