WITH f AS (
    SELECT FISH_TYPE ,COUNT(*) AS FISH_COUNT
    FROM FISH_INFO i
    GROUP BY FISH_TYPE
),
nf AS (
    SELECT n.FISH_TYPE , n.FISH_NAME , COALESCE(f.FISH_COUNT, 0) FISH_COUNT
    FROM FISH_NAME_INFO n
    RIGHT JOIN f ON (n.FISH_TYPE = f.FISH_TYPE)
)
SELECT t.FISH_COUNT , t.FISH_NAME
FROM nf t
ORDER BY FISH_COUNT DESC