WITH DISCOUNT AS (
    SELECT *
    FROM ((SELECT *
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE CAR_TYPE = "트럭")
    UNION
    (SELECT 999, "트럭", "0일 이상", 0)) AS T
)

SELECT HISTORY_ID
    ,FLOOR(DAILY_FEE * (DATEDIFF(END_DATE, START_DATE)+1) * (100-DISCOUNT_RATE)/100) AS FEE
FROM CAR_RENTAL_COMPANY_CAR
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY
    USING(CAR_ID)
JOIN DISCOUNT
    USING(CAR_TYPE)
WHERE CAR_TYPE = "트럭"
    && (DATEDIFF(END_DATE, START_DATE)+1 < 7 && DURATION_TYPE LIKE "0일%"
    || DATEDIFF(END_DATE, START_DATE)+1 BETWEEN 7 AND 29 && DURATION_TYPE LIKE "7일%"
    || DATEDIFF(END_DATE, START_DATE)+1 BETWEEN 30 AND 89 && DURATION_TYPE LIKE "30일%"
    || DATEDIFF(END_DATE, START_DATE)+1 >= 90 && DURATION_TYPE LIKE "90일%")
ORDER BY FEE DESC, HISTORY_ID DESC