SELECT F.FLAVOR
FROM FIRST_HALF AS F
RIGHT JOIN JULY AS J
    USING (SHIPMENT_ID)
GROUP BY J.FLAVOR
ORDER BY SUM(F.TOTAL_ORDER)+SUM(J.TOTAL_ORDER) DESC
LIMIT 3

# -- 코드를 입력하세요
# SELECT FLAVOR
# FROM (
#     (SELECT *
#     FROM FIRST_HALF)
#     UNION ALL
#     (SELECT *
#     FROM JULY)
# ) AS T
# GROUP BY FLAVOR
# ORDER BY SUM(TOTAL_ORDER) DESC
# LIMIT 3