WITH RECURSIVE T AS (
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR+1
        FROM T
        WHERE HOUR < 23
)

SELECT HOUR, COALESCE(COUNT, 0) AS COUNT
FROM (SELECT HOUR(DATETIME) AS HOUR, COUNT(*) AS COUNT
FROM ANIMAL_OUTS
GROUP BY HOUR) AS OUTS
RIGHT JOIN T
    USING(HOUR)