-- 코드를 입력하세요
 SELECT MEMBER_ID, MEMBER_NAME, GENDER, DATE_FORMAT(DATE_OF_BIRTH, "%Y-%m-%d") DATE_OF_BIRTH
-- SELECT *
FROM MEMBER_PROFILE
WHERE GENDER = 'W' && MONTH(DATE_OF_BIRTH) = 3 && !ISNULL(TLNO)
ORDER BY MEMBER_ID