WITH SCORE_TABLE AS(
    SELECT EMP_NO, YEAR, AVG(SCORE) AS SCORE
FROM HR_GRADE
GROUP BY EMP_NO,YEAR
)

SELECT EMP_NO, EMP_NAME
    , CASE 
        WHEN SCORE >= 96 THEN "S"
        WHEN SCORE >= 90 THEN "A"
        WHEN SCORE >= 80 THEN "B"
        ELSE "C"
     END AS GRADE
    , CASE 
        WHEN SCORE >= 96 THEN SAL*0.2
        WHEN SCORE >= 90 THEN SAL*0.15
        WHEN SCORE >= 80 THEN SAL*0.1
        ELSE 0
     END AS BONUS
FROM SCORE_TABLE
JOIN HR_EMPLOYEES
    USING (EMP_NO)
JOIN HR_DEPARTMENT #이거 왜 있는거임?
    USING(DEPT_ID)
ORDER BY EMP_NO