-- 코드를 입력하세요
SELECT MEMBER_NAME, REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE, "%Y-%m-%d") AS REVIEW_DATE
FROM (
    SELECT MEMBER_ID, MEMBER_NAME
    FROM MEMBER_PROFILE
    JOIN REST_REVIEW
        USING(MEMBER_ID)
    GROUP BY MEMBER_NAME
    ORDER BY COUNT(*) DESC
    LIMIT 1
    ) AS T
JOIN REST_REVIEW
    USING(MEMBER_ID)
ORDER BY REVIEW_DATE, REVIEW_TEXT