SELECT SUM(SCORE) AS SCORE
    , EMP_NO
    , EMP_NAME
    , POSITION
    , EMAIL
FROM HR_GRADE
JOIN HR_EMPLOYEES
    USING(EMP_NO)
JOIN HR_DEPARTMENT
    USING(DEPT_ID)
WHERE YEAR = 2022
GROUP BY EMP_NO
ORDER BY SUM(SCORE) DESC
LIMIT 1