-- 코드를 입력하세요
SELECT CATEGORY, PRICE AS MAX_PRICE, PRODUCT_NAME
FROM (
    SELECT *,
    RANK() OVER (PARTITION BY CATEGORY ORDER BY PRICE DESC) AS R
    FROM FOOD_PRODUCT
    WHERE CATEGORY = "과자" || CATEGORY = "국" || CATEGORY = "김치" || CATEGORY = "식용유"
     ) AS T
WHERE R = 1
ORDER BY MAX_PRICE DESC